Added accountClient v2 health and service checks
tozny/e3db-clients-go pull request #139
Opened 2020-11-26 00:36 UTC by carrala

Eli & I decided to add HostV2 to the E3dbAccoundClient so that these tests can be done, but I would like feedback on how other people think this should be done.
We're thinking there are three options:
1. 1 client with hosts for v1 and v2
2. 2 different clients with 1 host each
3. 1 client with 1 host where checks are managed by Cyclops

2020-11-26 00:42 UTC, efabens commented
Option three is that the host must be cyclops so that it does the routing. Slightly cleaner but causes potential minor backwards incompatibility issues and means you can't hit both services directly if there is a want to do that

2020-11-26 00:42 UTC, efabens approved these changes
Assuming folks are happy with the configuration change

2020-11-26 00:43 UTC, galxy25 requested changes
Refactor to either 1 account client, code should be able to create v1 and v2 clients but with a different host, e.g.

```go
accountServiceV1Client := accountClient.New({config with v1 host goes here})
accountServiceV2Client  :=  accountClient.New({config with v2 host goes here})
```

or 2 clients (basically create a new client in a file called accountClientV2.go

2020-11-26 00:45 UTC, efabens commented
Let's do two files/cleints then. Because just specifying different hosts for the same methods has the potential for unexpected outcomes and lots of 404s if you don't realize

2020-11-30 21:05 UTC, efabens reviewed
Couple of very minor nits

2020-11-30 21:05 UTC, efabens commented on accountClient/accountClientV2.go
> +//E3dbAccountClient implements an http client for communication with an e3db Account service.
Space between // and text

2020-11-30 21:05 UTC, efabens commented on accountClient/accountClientV2.go
> +//HTTP PATH prefix for calls to the e3db Account service for v1 and v2
This should just be v2

2020-11-30 21:05 UTC, efabens commented on accountClient/accountClient.go
> +//HTTP PATH prefix for calls to the e3db Account service for v1 and v2
this should just be v1

2020-11-30 21:39 UTC, galxy25 commented on accountClient/accountClient.go
> +// ProxyiedRegisterClient registers a client via a proxied call to client service by the account service.
Thank you

2020-11-30 21:40 UTC, galxy25 commented on accountClient/accountClientV2.go
> +func (c *E3dbAccountClientV2) ServiceCheckV2(ctx context.Context) error {
no V2 suffix needed for these methods now that they're part of a separate client

2020-11-30 21:41 UTC, galxy25 commented on accountClient/accountClient_test.go
> +	ValidClientConfigV2 = e3dbClients.ClientConfig{
Is this still needed?

2020-11-30 21:41 UTC, galxy25 approved these changes

2020-12-02 17:44 UTC, merged