List Group Endpoint
tozny/e3db-clients-go pull request #140
Opened 2020-11-30 17:44 UTC by rosasck

2020-11-30 19:24 UTC, galxy25 commented on storageClient/storageClient.go
> +	request, err := e3dbClients.CreateRequest("GET", path, params)
Get should have nil for params

2020-11-30 19:27 UTC, galxy25 commented on storageClient/storageClient.go
> +	request, err := e3dbClients.CreateRequest("GET", path, params)
Encode the next token and max as optional url query params

Encode the client_id as an optional url query param, that way be default when you call list groups you get all groups for your account, but you can optionally have the server filter out / only return groups for the requested client id

Examples of passing query params
https://github.com/tozny/e3db-clients-go/blob/master/identityClient/identityClient.go#L202
https://github.com/tozny/e3db-clients-go/blob/master/pdsClient/pdsClient.go#L310

2020-11-30 19:28 UTC, galxy25 commented on storageClient/api.go
> +// ListGroupsRequest wraps values used to Look up Groups a client is associated with
`look up groups for the client's account by default or optionally filter by parameters such as client ID`

2020-11-30 19:29 UTC, galxy25 commented on storageClient/storageClient.go
> +// ListGroups returns all the groups a client is associated with (if any).
`returns all groups for the client's account by default or optionally filter by parameters such as client ID`

2020-11-30 19:31 UTC, galxy25 commented on storageClient/api.go
> +// ListGroupsResponse wraps the list of groups a client is associated with
`wraps a collection of groups`, associated with a client is maybe the only filter we have for today but in the future we could have other

2020-11-30 19:31 UTC, galxy25 requested changes
see comments

2020-12-01 21:44 UTC, efabens approved these changes

2020-12-04 17:51 UTC, rosasck commented
Copy pasta Happy path Tests :)

2020-12-04 18:20 UTC, galxy25 commented on storageClient/api.go
> +	EncryptedGroupKey string `json:"encrypted_group_key"`
Reminder to update the swagger spec for this accordingly

2020-12-04 18:21 UTC, galxy25 commented on storageClient/api.go
> +	Index        int64     `json:"idx"`
This actually shouldn't get returned / exposed via our API, its an internal implementation detail of our db and pagination system.

2020-12-04 18:22 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	//ClientConfig.AuthNHost = cyclopsServiceHost
This can be removed right?

2020-12-04 18:25 UTC, galxy25 commented on storageClient/storageClient_test.go
> +		t.Fatalf("Group LIST: Group was Not Found: %+v ", responseList)
log the error

2020-12-04 18:26 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	//queenClient := storageClient.New(queenClientInfo)
also ripe for removal

2020-12-04 18:27 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	}
this test is almost complete, suggest also checking that the response contains a group with the same id as returned on line 503

2020-12-04 18:28 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	t.Log(responseList)
this can be removed, test that the response contains the group created on line 456

2020-12-04 18:29 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	}
verify that the response contains both created groups

2020-12-04 18:30 UTC, galxy25 commented on storageClient/storageClient_test.go
> +		t.Fatalf("Group DELETE: Group was not Deleted: %+v ", group)
log the error as well

2020-12-04 18:30 UTC, galxy25 approved these changes
approved pending resolution of comments

2020-12-04 19:11 UTC, galxy25 commented on storageClient/storageClient_test.go
> +	}
comment above should not be marked as resolved

2020-12-05 00:37 UTC, rosasck commented
Fixed Tests desired outcome, and endpoint to send desired errors

2020-12-05 04:43 UTC, galxy25 approved these changes

2020-12-07 17:46 UTC, merged