Secret key sizes
tozny/e3db-clients-go pull request #178
Opened 2021-05-05 20:50 UTC by carrala

these key length constants are used to check that the key lengths in a client credential object are valid.

2021-05-05 20:59 UTC, rosasck approved these changes

2021-05-05 23:01 UTC, efabens requested changes
I think that these are for base64 encoded length, which doesn't feel like the appropriate way to validate a key length, and so I would hesitate to have them be constants.

2021-05-05 23:14 UTC, galxy25 commented
> I think that these are for base64 encoded length, which doesn't feel like the appropriate way to validate a key length, and so I would hesitate to have them be constants.

@efabens would you recommend that the go SDK should decode a credential secret (which btw would be nice to have such a function to convert from dashboard json string to go sdk creds 🤔 ) from string into the bytes and use the existing type to validate? The current approach follows the logic of the js-sdk where we aren't doing such a conversion.

@carrala at the very least we need to resolve the "why are these lengths different then the raw byte length", e.g. if these are base64 encoded version (which I believe they are), then the names should be  like `Base64EncodedPublicSigningKeyLength`. It's obnoxious (what is this, a java spring class name?) but less so if you think about the amount of confusion that has been generated by this ambiguity just in the past week, can you imagine how much longer it would take future developers to figure that out?

2021-05-05 23:30 UTC, efabens commented
Yes, that was the recommendation that I put here https://github.com/tozny/e3db-go/pull/57#discussion_r626905035
I would agree it is not what we do for the js-SDK. There is some additional computation cost it does mitigate any risk of padding issues that might come up, though we have strict rules on that and so rejecting based on base64 encoded in that case might be better as we want to ensure padding is correct.

2021-05-05 23:44 UTC, carrala commented
> Yes, that was the recommendation that I put here [tozny/e3db-go#57 (comment)](https://github.com/tozny/e3db-go/pull/57#discussion_r626905035)
> I would agree it is not what we do for the js-SDK. There is some additional computation cost it does mitigate any risk of padding issues that might come up, though we have strict rules on that and so rejecting based on base64 encoded in that case might be better as we want to ensure padding is correct.
> 
> I am not strongly opinionated about converting to bytes vs renaming the constant. @galxy25 @carrala
> 
> As a note we do have a way to go from dashboard json to go sdk creds in that we can json unmarshal and there is a method to take that struct I believe

This does look like a nicer, less hack-y way to check if the credential format is correct. In that case I won't need these new keys. If that works, I'll close this PR & add the changes to the e3db-go PR. @efabens @galxy25

2021-05-05 23:46 UTC, galxy25 commented
> Yes, that was the recommendation that I put here [tozny/e3db-go#57 (comment)](https://github.com/tozny/e3db-go/pull/57#discussion_r626905035)
> I would agree it is not what we do for the js-SDK. There is some additional computation cost it does mitigate any risk of padding issues that might come up, though we have strict rules on that and so rejecting based on base64 encoded in that case might be better as we want to ensure padding is correct.
> 
> I am not strongly opinionated about converting to bytes vs renaming the constant. @galxy25 @carrala
> 
> As a note we do have a way to go from dashboard json to go sdk creds in that we can json unmarshal and there is a method to take that struct I believe

@carrala @efabens I'm fine with either approach (with a slight bias to the current approach with minor re-naming since it currently works and is compatible with how the Identity portal works). Note that for the byte based approach a plain json unmarshal will give you the base64 string value of the key and not the raw bytes, we'll want reverse versions of this sort of method https://github.com/tozny/e3db-clients-go/blob/master/crypto.go#L62 to do byte length validation.

2021-05-06 19:15 UTC, efabens approved these changes

2021-05-06 20:00 UTC, galxy25 commented on crypto.go
> +	FILE_BLOCK_SIZE                      = 65536
now in this repo, since there is some more consistency than in e3db-go, please use CamelCase for constants

2021-05-06 20:00 UTC, galxy25 approved these changes

2021-05-06 22:20 UTC, merged